### ISSUE TITLE
Possible typo in src/cast.ls?

### ISSUE THREAD

**Issue by platinumazure** [gkz/levn#3]
Hi, first of all, just want to say thanks for working on a fix for #2! Really appreciate it, and this is going to help the ESLint project.

I happened to read through the diff, and I'm wondering if there is a typo that could cause problems in the latest release. There is a token "repalce", which I assume would be "replace". See below link to review in context.

https://github.com/gkz/levn/blob/0c5f341936715f9dc4be60c7141ec5eb0769f536/src/cast.ls#L64

If I'm totally wrong, then I apologize for wasting your time. Please feel free to close the issue if that is the case.

**Comment by gkz** [comment]
Thanks
